### ISSUE TITLE
Separate Internet Explorer More*

### ISSUE THREAD

**Issue by MoscaDotTo** [MoscaDotTo/Winapp2#144]
Currently this entry looks like this 

[Internet Explorer More *]
LangSecRef=3022
Detect=HKCU\Software\Microsoft\Internet Explorer
Default=False
FileKey1=%AppData%\Microsoft\Internet Explorer|brndlog.bak;brndlog.txt
FileKey2=%AppData%\Microsoft\Internet Explorer\UserData|*.*|RECURSE
FileKey3=%LocalAppData%\Microsoft\Internet Explorer|frameiconcache.dat;tabiconcache.dat;brndlog.txt;brndlog.bak
FileKey4=%LocalAppData%\Microsoft\Internet Explorer\Recovery\Last Active|*.*|RECURSE
FileKey5=%LocalAppData%\Microsoft\SmartScreen|*.tmp
FileKey6=%LocalAppData%\Microsoft\Windows\*Cache*|*.*|RECURSE
FileKey7=%LocalLowAppData%\Microsoft\Internet Explorer\iconcache|*.*|RECURSE
FileKey8=%LocalLowAppData%\Microsoft\Windows\AppCache|*.*|RECURSE
FileKey9=%SystemDrive%\Documents and Settings\*Service\IETldCache|*.*|RECURSE
FileKey10=%SystemDrive%\Documents and Settings\Default User\Application Data\Microsoft\Internet Explorer|brndlog.bak;brndlog.txt
FileKey11=%WinDir%\ServiceProfiles\*Service\AppData\Roaming\Microsoft\Windows\IETldCache|*.*|RECURSE
FileKey12=%WinDir%\System32\config\Systemprofile\AppData\Local\Microsoft\Windows\INetCache|*.*|RECURSE
FileKey13=%WinDir%\System32\config\SystemProfile\AppData\LocalLow\Microsoft\Internet Explorer|brndlog.bak;brndlog.txt
FileKey14=%WinDir%\System32\config\SystemProfile\Application Data\Microsoft\Internet Explorer|brndlog.bak;brndlog.txt
RegKey1=HKCU\Software\Microsoft\Internet Explorer\International|CNum_CpCache
RegKey2=HKCU\Software\Microsoft\Internet Explorer\International|CpCache
RegKey3=HKCU\Software\Microsoft\Internet Explorer\International\CpMRU
RegKey4=HKCU\Software\Microsoft\Internet Explorer\LowRegistry\Audio\PolicyConfig\PropertyStore
RegKey5=HKCU\Software\Microsoft\Internet Explorer\Main\FeatureControl
RegKey6=HKCU\Software\Microsoft\Internet Explorer\PageSetup
RegKey7=HKCU\Software\Microsoft\Internet Explorer\Recovery\PendingDelete
RegKey8=HKCU\Software\Microsoft\Internet Explorer\TypedURLSTime
RegKey9=HKCU\Software\Microsoft\Windows\CurrentVersion\Ext\Stats
ExcludeKey1=FILE|%LocalAppData%\Microsoft\Windows\INetCache\IE\|container.dat

As part of the refactor, it feels appropriate to break this entry into separate parts to give the granularity one would expect in additional web browser cleaning (ie. History should not be cleaned alongside the cache) 

I'm not familiar with IE, so hoping someone who knows a bit about it could look at this

**Comment by ROCKNROLLKID** [comment]
Unfortunately, I don't know anything about IE either. I haven't used that since 2009. All the ones that have cache in it are obviously cache related, but that's all I can tell you.

**Comment by dvdbane** [comment]
i'm not familiar too with IE but after some testing, i found

new [Internet Explorer More *] clean \AppData\Local\Microsoft\Windows\Caches\
this is due to FileKey6=%LocalAppData%\Microsoft\Windows\*Cache*|*.*|RECURSE
is this intended action?

ccleaner IE history clean this location
C:\Users\User\AppData\Local\Microsoft\Internet Explorer\Recovery\Last Active\
if we're gonna keep this entry in main winapp2.ini, just remove FileKey4
FileKey4=%LocalAppData%\Microsoft\Internet Explorer\Recovery\Last Active|*.*|RECURSE

ccleaner already cover these location
**C:\Users\User\AppData\Local\Microsoft\Windows\INetCache\IE\**ZGF047XZ\WQAUSD9R	0 KB
**C:\Users\User\AppData\Local\Microsoft\Windows\INetCache\Low\**MSIMGSIZ.DAT	48 KB
**C:\Users\User\AppData\Local\Microsoft\Windows\INetCache\Virtualized\**C\ProgramData\NVIDIA Corporation\Drs\nvAppTimestamps	4 KB | this rule use recurse if i'm not mistaken


what left after comparing both cleaning result [Internet Explorer More *] vs cc [Internet Explorer]
of course these extra belong to [Internet Explorer More *]

C:\Users\User\AppData\Local\Microsoft\Windows\AppCache\6X6F3ZA4\container.dat	0 KB
C:\Users\User\AppData\Local\Microsoft\Windows\AppCache\container.dat	0 KB
C:\Users\User\AppData\Local\Microsoft\Windows\Caches\cversions.1.db	16 KB
C:\Users\User\AppData\Local\Microsoft\Windows\Caches\cversions.3.db	16 KB
C:\Users\User\AppData\Local\Microsoft\Windows\Caches\{384756BA-B905-4D30-88C9-B63C603DA134}.3.ver0x0000000000000001.db	368 KB
C:\Users\User\AppData\Local\Microsoft\Windows\Caches\{3DA71D5A-20CC-432F-A115-DFE92379E91F}.1.ver0x000000000000012b.db	155 KB
C:\Users\User\AppData\Local\Microsoft\Windows\Caches\{3DA71D5A-20CC-432F-A115-DFE92379E91F}.1.ver0x000000000000012d.db	157 KB
C:\Users\User\AppData\Local\Microsoft\Windows\Caches\{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x00000000000000cc.db	90 KB
C:\Users\User\AppData\Local\Microsoft\Windows\Caches\{AFBF9F1A-8EE8-4C77-AF34-C647E37CA0D9}.1.ver0x00000000000000cd.db	142 KB
C:\Users\User\AppData\Local\Microsoft\Windows\IECompatCache\container.dat	0 KB
C:\Users\User\AppData\Local\Microsoft\Windows\IECompatCache\Low\container.dat	0 KB
C:\Users\User\AppData\Local\Microsoft\Windows\IECompatUACache\container.dat	0 KB
C:\Users\User\AppData\Local\Microsoft\Windows\IECompatUACache\Low\container.dat	0 KB
C:\Users\User\AppData\Local\Microsoft\Windows\INetCache\Low\IE\container.dat	0 KB
C:\Users\User\AppData\Local\Microsoft\Windows\WebCache\V01.chk	8 KB
C:\Users\User\AppData\Local\Microsoft\Windows\WebCache\V0100023.log	512 KB
C:\Users\User\AppData\Local\Microsoft\Windows\WebCache\V0100024.log	512 KB
C:\Users\User\AppData\Local\Microsoft\Windows\WebCache\V01res00001.jrs	512 KB
C:\Users\User\AppData\Local\Microsoft\Windows\WebCache\V01res00002.jrs	512 KB
C:\Users\User\AppData\Local\Microsoft\Windows\WebCache\V01tmp.log	512 KB
C:\Users\User\AppData\LocalLow\Microsoft\Windows\AppCache\B3ARVT4F\container.dat	0 KB
C:\Users\User\AppData\LocalLow\Microsoft\Windows\AppCache\container.dat	0 KB
C:\WINDOWS\System32\config\Systemprofile\AppData\Local\Microsoft\Windows\INetCache\counters.dat	1 KB


i don't think we need to make it separate again because it's all cache

**Comment by MoscaDotTo** [comment]
I believe this has been addressed in #138 as of now, so I will close this.
