### ISSUE TITLE
[WinappDebug] Several false positives with current Winapp2

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#159]
It seems there are several false positives with the current copy of Winapp2 using WinappDebug. Several say some entries need to be moved when they don't, while some say they need to be moved to the exact same spot (example: current line 1000, expected line 1000).

**Comment by MoscaDotTo** [comment]
Can you provide the output you're seeing problems with? I'm testing WinappDebug against the current winapp2.ini and I am not seeing any false positives. Typically if you see a matching expected and current positioning, there is a second line in the same entry that also needs to be moved, but WinappDebug is not smart enough to know the ending line position of commands who are out of place only because another line (or lines) is. These lines are typically fixed implicitly by correcting the line whose position differs from its expected. 
eg.

![image](https://user-images.githubusercontent.com/529203/34688084-ea7c6f86-f47e-11e7-8430-89adb87379b4.png)

Here, correcting the position of FileKey5 (actually should be FileKey4, which the output corrects for automatically but requires manual editing in the file) to line 7775 would mean implicitly that the line at 7775 would move to 7776. On a subsequent run of WinappDebug, these lines will be in the correct positions. 

![image](https://user-images.githubusercontent.com/529203/34688183-424bcf9a-f47f-11e7-9e4a-46d5e9ee2360.png)

This is little quirk in the debugger that I left in primarily to make sure it didn't overlook anything in case the "needs to move left" method was too naive - most of the time the second pass outputs things implied by the first, but situations where a command needs to move, say, from the 2nd position to the final position will be more easily revealed. This is why the phrasing at the bottom says *possible* errors

**Comment by ROCKNROLLKID** [comment]
Ok, I did not know that about the (current 1000, expected 1000) thing.

About the false positives, I was referring a few that are like this:

FileKey12=%ProgramFiles%\IObit\Advanced SystemCare *\*.cab_Temp|*.*|REMOVESELF
FileKey13=%ProgramFiles%\IObit\Advanced SystemCare *|*.log;*.txt|RECURSE

WinappDebug says that 13 need to be 12 and thought this was wrong, however, looking closer I realized that 12 has a \ and WinappDebug detects that this should come before |. I guess this is correct?

Anyways I will close since this got straighten out.

**Comment by MoscaDotTo** [comment]
Yes, | takes precedence in WinappDebug over \ 

this is so that %SomeDir%|somefiles comes "alphabetically" before %SomeDir%\SomeOtherDir|somefiles

**Comment by MoscaDotTo** [comment]
I believe I have addressed this issue in the winapp2ool debugger module, I can't say it'll be 100% accurate 100% of the time, but it should point to the proper line now at least most of the time (with a tweaked message to indicate that the line is most likely out of place due to another line also being out of place)

![image](https://user-images.githubusercontent.com/529203/34929326-3812889a-f991-11e7-9e47-51df96b36a0a.png)
