### ISSUE TITLE
Suggestion from the community

### ISSUE THREAD

**Issue by APMichael** [MoscaDotTo/Winapp2#188]
**Locke** wrote:

"Hey guys.

Since you've decided to do an overhaul of winapp2, here's a suggestion:

Do you think you could group Games rules all together like you did with browser rules? Kinda makes sense to separate them from apps.

Thanks for your efforts and keep up the good work!"

https://forum.piriform.com/topic/32310-winapp2ini-additions/?page=282&tab=comments#comment-292486

What do you think about it? There are currently 378 game entries. Do Winapp2ool need an update first?

**Comment by MoscaDotTo** [comment]
I'm not explicitly for this change. The browser sections are nice because [most] of their contents are multiple entries that relate to the same piece of software, the general exception being alternative browsers whose support isn't included in CCleaner (7Star, eg.) 

 Games do not share this trait; they're just all in the same section. We don't otherwise group the "Applications" or "Multimedia" together into a single bloc, so I don't think we should do the same for games.

**Comment by APMichael** [comment]
Yes, you are right. If we start grouping the game entries then we have to group the applications (according to theirs LangSecRef) also. And that isn't really necessary.

**Comment by ROCKNROLLKID** [comment]
Browsers also update quite often then any other software and something seems to always need to be changed or added or removed, so having them on top made sense and was easier for future editing.

**Comment by APMichael** [comment]
Thanks for your replies. I think we can close this thread now.
