### ISSUE TITLE
How long should we support old/discontinued software?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#275]
Continuing from: https://github.com/MoscaDotTo/Winapp2/issues/274

"The browsers Flock and Rockmelt are officially discontinued. Shouldn't we remove them? Using an outdated browser is a massive security flaw. Coowon and ChromePlus/CoolNovo seems to be discontinued also."

I feel like maybe we should make a EOL date for old versions/discontinued software. Obviously, it would be wrong to remove it right after it gets discontinued, as there are still lots of users that may be using it. Yes it's true running outdated software is a security risk, however, software like browsers can easily be run through a sandbox, too, and maybe some people still like/use these outdated software. I also don't want to consume Winapp2 space by added such outdated software in Winapp2.

So I purpose a solution. I say that, depending on how popular that program is, if it is not so popular, we support it for 3 years after it's last update, and if it is still pretty popular, then we extend it to 5 years after it's last update. The reason why I think this is a great idea is because, for example, Windows XP is discontinued for 4 years now, but OS stats and market share still show 3-5% users still on Windows XP. That could be hundreds of thousands of users. It would be wrong to exclude so many.

**Comment by MoscaDotTo** [comment]
I don't think it really matters how big the file is given the simplicity of trimming it (provided by both winapp2ool and ccenhancer, perhaps other tools unknown) but if we wanted to EOL software in winapp2.ini I think a good solution would be to implement the entries into some separate ini file.

Removed Entries contains entries removed from winapp2.ini because they were implemented in ccleaner but we could also provide a set of entries removed because the software has been discontinued. 

I think it's good to keep this information around even after its outlived its "usefulness" to easily support "out there" legacy configurations

**Comment by ROCKNROLLKID** [comment]
I think we will just leave it how it is and maybe after a long time, we can consider removing them.

**Comment by APMichael** [comment]
Is ok for me too.
