### ISSUE TITLE
[Opera] Add items from chromium-based browsers to Opera

### ISSUE THREAD

**Issue by KosMos-pv** [MoscaDotTo/Winapp2#306]
There is a lot of folders that are the same as in Chrome, but they are not present in this file. For example Extensions Databases, Extensions State, FlashPlayer AssetCache, FlashPlayer SharedObjects and other entries from Chrome. There is only entries for old Opera versions below 15. CCleaner can clean some chromium-based folders from Opera profile but not all that Winapp2 can do.

**Comment by APMichael** [comment]
Thanks for your suggestion. We can add Opera to all the Chrome entries.

The path to the user data should be:
"%AppData%\\Opera Software\\Opera Stable\\"

Is the registry key on your system also like that:
HKEY_CURRENT_USER\\Software\\Opera Software\\dbff851fa759ccb33e726f883720ae50\\

Correct?

**Comment by KosMos-pv** [comment]
I have some different key, so I think only part without last number is needed.
My key is HKEY_CURRENT_USER\Software\Opera Software\098985b9df559691589538890aa60adc
Also there can be beta and developer versions of Opera so path to look into files should be like this:
"%AppData%\Opera Software\Opera*\"

**Comment by APMichael** [comment]
Thanks for your reply.

Ok, then we cannot add Opera to the entry [Browser Exit Codes *], because of the strange registry key. But I think that is not tragic.

We will add Opera with the following paths:
Registry Key: "HKCU\\Software\\Opera Software"
Profile Path: "%AppData%\\Opera Software\\Opera\*"
Application Path: "%LocalAppData%\\Programs\\Opera\*" (Installation type: "Install per user")
Application Path: "%ProgramFiles%\\Opera\*" (Installation type: "Install for all users")

**Comment by KosMos-pv** [comment]
I think it's okay because I did not find Browser Exit Codes for Opera in my registry. Maybe this is specific only for Chrome itself but I see these entries for other chromium-based browsers. But I don't have any of them to test.

**Comment by APMichael** [comment]
Ok, thanks for checking and your reply.

**Comment by APMichael** [comment]
I opened a new pull request (#307).
