### ISSUE TITLE
How to use command line options 

### ISSUE THREAD

**Issue by CSGalloway** [MoscaDotTo/Winapp2#362]
I would like to download the latest 
- winapp2.ini 
- winapp3.ini 
merge "C:\Z_Z_WorkHere\INI_001\custom.ini"

and winapp2ool.exe is stored in the CCleaner folder.
===============
Also to download the winapp2ool readme file...

**Comment by MoscaDotTo** [comment]
Add the -s flag to any line to have winapp2ool suppress its output and close when the task is finished

`winapp2ool.exe -6 1` downloads winapp2.ini (the "main" file - replace 1 by 2 for the non-ccleaner variant) 
`winapp2ool.exe -6 5` downloads winapp3.ini 

`winapp2ool.exe -3 -w -3d OUTPUT_PATH_HERE` - This will open merge, use the local winapp3.ini found in the current directory, and output the merged file to the specified path. 

I'll be making some surface level commandline handler changes soon that should introduce more plaintext into the commands to make them less confusing (ie. specifying 'winapp2' as the download file rather than using 1)

**Comment by CSGalloway** [comment]
1) How would I merge "C:\Z_Z_WorkHere\INI_001\custom.ini"

2) Can i download winapp2.ini and winapp3.ini at the same time?

Thank you...

**Comment by MoscaDotTo** [comment]
`winapp2ool.exe -3 -2d C:\Z_Z_WorkHere\INI_001\custom.ini' will merge custom.ini from the given path to winapp2.ini in the current folder

**Comment by MoscaDotTo** [comment]
There is currently no way to download multiple files at once but I will investigate it

**Comment by CSGalloway** [comment]
The quoted command below will do what please? Merge winapp3.ini into
winapp2.ini then merge the new file to what name in OUTPUT_PATH_HERE ?

**Comment by CSGalloway** [comment]
I am receiving:

Error: System.IndexOutOfRangeException: Index was outside the bounds of the
array.
   at winapp2ool.iniFileHandler.iniKey..ctor(String line, Int32 count)
Please report this error on GitHub
Press Enter to continue

the custom.ini is attached.....

**Comment by MoscaDotTo** [comment]
custom.ini does not seem to have come through

> The quoted command below will do what please? Merge winapp3.ini into winapp2.ini then merge the new file to what name in OUTPUT_PATH_HERE ?

 winapp2ool.exe -3 -w -3d OUTPUT_PATH_HERE

`-3` for merge
`-w` to select winapp3.ini as the "second file" (ie. the file to be merged into winapp2.ini which is the "first file") 

`-w` here is the same as `-2f winapp3.ini` or `-2d PATH_TO_CURRENT_FOLDER\winapp3.ini` 

`-3d OUTPUT_PATH_HERE`

 the output file is the "third file", and is otherwise empty until the end of whatever process is going on in a module. It holds only the information of where to save the file. If you want to save to a file different than the winapp2.ini file in the same folder as winapp2ool, you specify this using `-3d` or `-3f`

If you're still having trouble, try using the winapp2ool in Branch1, it has some more recent changes to commandline handler that may have fixed some bugs.

**Comment by CSGalloway** [comment]
I have uploaded custom.ini and custom.bat to my onedrive and shared the
folder as:

      https://1drv.ms/f/s!Ap7yFWW-HrgerxVpwCMJkFNVz9rr

What is the URL to download the EXE from branch 1 please?

**Comment by CSGalloway** [comment]
Does the custom.bat look right with you?

**Comment by MoscaDotTo** [comment]
The custom.bat worked fine for me. The only thing I would change would be to add a -s to each command so that you needn't manually close each winapp2ool instance.
