### ISSUE TITLE
[Winapp2ool] trimmer doesn't support Winapp3 anymore & gets rid of its entries

### ISSUE THREAD

**Issue by Dutchman101** [MoscaDotTo/Winapp2#368]
Since the latest updates of Winapp2ool, the tool no longer supports the contents of Winapp3.ini in the following ways:

- It will replace Winapp3 content with the latest Winapp2 (fetched) when you rename an original Winapp3 to Winapp2 in order to trim it

- It will cut out Winapp3 entries from Winapp2.ini if Winapp3 was merged into Winapp2 or other personalised entries.

My personal habit, as advanced user, was to combine Winapp2 with Winapp3 (custom copy paste) to perform a power clean with all thinkable entries, accepting the risks but without ever getting problems.
Now, the dangerous entries (Winapp3) will be deleted by WInapp2ool when ran over this merged ini. I consider this annoying, as that means I first need to trim Winapp2 and then paste Winapp3 entries into it afterwards, also being unable to optimize said additions like before.

I understand if the trimming tool now checks the entries integrity/version from remote, and I don't know if the same (or similar) problems now happen to any other custom ini's, but I hope you can improve the new Winapp2ool behaviour to tolerate at least the scenario I described better.

**Comment by Dutchman101** [comment]
Alternatively, if it's difficult to get around this issue, I would suggest to make the following practise easier;

> My personal habit, as advanced user, was to combine Winapp2 with Winapp3 (custom copy paste) to perform a power clean with all thinkable entries, accepting the risks but without ever getting problems

By offering something like Winapp4.ini, which combines both Winapp versions by default. And then eventually optimizing Winapp2ool's compatibility with that version. I considered to suggest a merge release before, but this gives me a good occasion.

**Comment by APMichael** [comment]
Did you disable "Download" (2. Toggle Download)? It is now enabled by default and therefore Trim ignores your local winapp2.ini file.

Alternatively, you can also download the latest beta, which has disabled the automatic download again:
https://github.com/MoscaDotTo/Winapp2/blob/Branch1/winapp2ool/bin/Debug/winapp2ool.exe

**Comment by MoscaDotTo** [comment]
Please note that the beta branch may have some instability issues as I'm in the process of writing regression tests which involves replacing some (a lot) of plumbing.

**Comment by Dutchman101** [comment]
> Did you disable "Download" (2. Toggle Download)? It is now enabled by default and therefore Trim ignores your local winapp2.ini file.
> 

My problem is solved after disabling that.
Feedback: maybe having it disabled by default is enough, users that want to fetch the latest and discard all their custom changes could still easily find that option. Now, it's easily carried out without realising.

Alternatively, you could check if the beginning of the Winapp2 file contains original content, because people tend to add customisations (such as Winapp3) at the bottom of the file anyways. So, when you update Winapp2 version with the trimmer, it will only do an insert operation in the range the tool decided Winapp2 was covered.

**Comment by APMichael** [comment]
Thank you for your reply. I think it will be disabled by default for the next release, as in the beta versions. The next release will also use colors, so it will be easier to see the status of an option.

**Comment by MoscaDotTo** [comment]
I will look into detecting when extended winapp2.ini files are present for a future release, as Michael mentioned, the next release will have color coded menu options. This currently takes the form of red = setting currently disabled and green = setting currently enabled, with red menu headers during errors as well, which should hopefully make the status of toggles like the downloads more readily evident than just the enabled/disabled string

![image](https://user-images.githubusercontent.com/529203/54225272-b9594600-44d1-11e9-917e-e382b16b6333.png)

![image](https://user-images.githubusercontent.com/529203/54225287-c37b4480-44d1-11e9-8abf-d4b20669d371.png)

![image](https://user-images.githubusercontent.com/529203/54225312-cc6c1600-44d1-11e9-8557-51300bcedb9b.png)

![image](https://user-images.githubusercontent.com/529203/54225327-d4c45100-44d1-11e9-92a0-0496a563b54c.png)

The effect is somewhat muted on my machine due to my light console background color, I believe. Feedback is encouraged 

(While I'd like to have only the text print in colors, menu lines are printed all at once including the border and this would require a pretty serious rewrite of how the menu printing logic works)
