### ISSUE TITLE
winapp2ool.exe

### ISSUE THREAD

**Issue by pc71520** [MoscaDotTo/Winapp2#375]
1) You need to find an **Icon** for the **winapp2ool.exe**, because it looks so Primitive Without an Icon for the .exe file.

2) Instead for the **Black** Color when running the winapp2ool.exe, you can use a nicer color:

:: Set console.
:: /************************************************************************************/
:mode
echo off
mode con cols=78 lines=30
color 17
cls
echo.

**Comment by MoscaDotTo** [comment]
I looked into setting the colors to something a little nicer but it turns out that the ability to do this in vb.net is somewhat constrained by the `Console` class that you'd use to assign the colors. 

There's some ways of working around this by defining new color pallets but it's not very well documented and wouldn't necessarily work across even versions of Windows 10 let alone older ones.

I'd recommend tackling this by setting the Properties for Winapp2ool (top left of the console window) and setting your preferred colors/fonts. The only drawback of this configuration is that it is not portable, in that if you move the executable to a different folder, you will need to reconfigure those properties.

**Comment by MoscaDotTo** [comment]
Oh! Also, winapp2ool adheres to your default console color settings. So if you configure *all* console windows to look some way you like, winapp2ool obeys this. 

![image](https://user-images.githubusercontent.com/529203/57105448-c687f980-6cf8-11e9-94a0-379f252ead5a.png)

You might find this tool helpful for picking a nicer pallet too: https://github.com/microsoft/console/releases

I use the OneHalfDark scheme
