### ISSUE TITLE
Overhaul all the game entries

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MoscaDotTo/Winapp2#388]
Most of our game entries are specific to one platform, such as steam install only, origin install only, etc. Since there are multiple platforms to install games from, we should make a effort to support all our entries on multiple platforms where it applies.

I sort of already started this with https://github.com/MoscaDotTo/Winapp2/pull/389

The targeted platforms for this would be Steam, GOG, Origin, Epic, and Battlenet. We could also try to support Uplay and Bethesda Launcher.

**Comment by decofona** [comment]
@ROCKNROLLKID what do you actually intent?


You want to add to all Game Entries which are there in Winapp2.ini, that we add GOG, Origin, Epic, Battlenet entries?

We could add them, which is good idea. Basically it will be always the same path for every game, but we only have to change it for every client.

**Comment by MoscaDotTo** [comment]
Not all games appear on all platforms and there's no guarantee that the paths will be the same. I was looking into which games appear on which platforms a while ago but struggled to find a tool to do so efficiently.

https://isthereanydeal.com could lend some insight perhaps

**Comment by decofona** [comment]
@MoscaDotTo I think we can close this issue then, because adding entries (be it application or game entries) is in ongoing goal of this project. There is no need then I think, as far as I understood.


We could add all entries generic, but there are two drawbacks:
1.) We have to add all these entries
2.) It will take more space for entries, which probably not exist.

The best approach if you ask me is an automated script, that will copy all filekeys of all entries, iterate one number up and add the next path.


For example lets take this entry:

[3 Stars of Destiny *]
Section=Games
Detect=HKCU\Software\Valve\Steam\Apps\278530
Default=False
FileKey1=%AppData%\3Stars|*.tmp


This would be like this after the automated script works:
[3 Stars of Destiny *]
Section=Games
Detect=HKCU\Software\Valve\Steam\Apps\278530
Default=False
FileKey1=%AppData%\3Stars|*.tmp
FileKey2=%ProgramFiles%\Steam (x86)\SteamApps\Common\3Stars|*.tmp
FileKey3=%SystemDrive%\GOG Games\3Stars|*.tmp
FileKey4=%ProgramFiles%\GOG.com\3Stars|*.tmp
FileKey5="%AppData%\Origin\3Stars|*.tmp
FileKey6=%ProgramFiles%\Epic Games\*\3Stars|*.tmp


Battlenet seem to have no default install directory.

**Comment by ROCKNROLLKID** [comment]
My intention was to make all entries multi-platform so they support all game launchers, since Steam is not the only place to buy games. As you can see in the PR I linked, I started this with a few entries and added support for Steam and Origin installs. As Robert mentioned, I didn't really find a easy way to do this as these platforms don't have a way to look up ids and thus require you to buy the games.

So, I just left this open in case anyone wanted to take this on.

Battle.net default install directory is program files.

**Comment by MoscaDotTo** [comment]
I think it's a worthwhile effort for "completeness" sake and a few observations about platforms can be made to significantly reduce the amount of detective work here:

Battle.net only has a handful of games and they're all Blizzard/Activision titles 

Indie games don't seem to appear on Origin or UPlay, but they can be found on GOG / DRM Free (humble? etc), and on Steam. 

I'm not sure whether Desura as a platform still exists, or what became of games accessed through their services. It might be worth segmenting Desura data away into an archive, since I don't think these games have been accessible for a few years

Other clients worth investigating the stores/ of are Twitch and Epic Games Store

**Comment by MoscaDotTo** [comment]
The easiest data to collect is the information of which games appear on which platforms, since this can be done from the store fronts. 

We should collect a some information about a few games that appear on multiple platforms; If we can establish that a general pattern exists (ie. games use the same paths between store fronts and the only major difference between platforms is the path of the platform) then leveraging winapp2ool to generate game content more dynamically should be fairly straightforward

**Comment by decofona** [comment]
@MoscaDotTo 

I think following two things can be done:

1.) Creating a List of Games on every Gaming Site like Steam, Origin.

2.) Having the default path find out for all the gaming software.

But we cannot do following:

1.) We don't know, which game produces which kind of temporary files (logs, temp).


For Example:

I know, that AC Origins is available for Steam and Ubisoft. And I can very easily find out from internet which is the default installation path for both of them.

But I don't know, which useless file it generating, even if it's generating, without installing the game. Installing the Game cannot be done without buying the game.

So in the end, this issue seems for me not important, because the main way of us generating winapp2.ini entries is, that a user is complaining, that he has found some kind of useless files and we are generating entries based on what the user gives us information about. Or some users on the forum generate the entries and share them with us.

So in the end, it's not working, even I would like to help very much.

However my last idea would be following, but I'dont know, if you would accept.
An entry, which cleans all kind of temporary files (log, tmp) in all kind of gaming systems like Steam, Origin. 

1.) This would however take a lot of time, if the user has installed a lot of games.
2.) This would perhaps clean important log or tmp files.
3.) This would not clean temporary files, which are known. For most games today have a redist folder, which contains dx9, donet, vbasic....

The best way is asking the community for games, which they have installed and ask them, if they know any files, which are tempory or not.

But this is only my humble opinion.
This would however

**Comment by ROCKNROLLKID** [comment]
The main issue is that even if we do find which games exist in which platforms, there is still no easy way to determine it's game id without buying them. Steam is easy because you do not need to own the game to find it's ID. You can simply look it up or go to the store page. However, Origin, Epic, GOG, etc do not seem to have a way to look up game IDs without owning them. If anyone has a way to look these up, please let us know. Otherwise, I think we can just close this then.

**Comment by novaceb881** [comment]
@ROCKNROLLKID 

I think we can close this issue now?
