### ISSUE TITLE
The characters searched in this site can not be deleted

### ISSUE THREAD

**Issue by pmboom18** [MoscaDotTo/Winapp2#393]
winapp2
Microsoft Edge Insider

https://www.bilibili.com/
The characters searched in this site can not be deleted
Do you need any other code?

Windows10 pro 64bit 1903

**Comment by APMichael** [comment]
Thank you for your information.

The following FileKey is required for complete cleaning:
`%LocalAppData%\Microsoft\Edge*\User Data\*\Local Storage\leveldb|*.*`

We will add it with the next update.

**Comment by APMichael** [comment]
Unfortunately, we have received the message that the FileKey affects extensions. So we can't include it in the Winapp2.ini, but in the Winapp3.ini.

You can copy the new entry from Winapp3.ini and paste it into a Custom.ini and then use Winapp2ool to download the latest Winapp2.ini and merge it with the Custom.ini. Or you can wait until CCleaner officially supports the Chromium-based Edge, because the entry "Cookies" will clean the LevelDB in a different way.
