### ISSUE TITLE
Check for duplicates

### ISSUE THREAD

**Issue by az0** [MoscaDotTo/Winapp2#45]
ROCKNROLLKID pointed out WinappDebug is similar in spirit to my merge-commit.sh script, so what do you think about adding all the functionality in one place?

In particular:
- Check for duplicate sections like `[Foo*]` twice
- Check for duplicate options like `FileKey2=...` twice within one section (see #43 )

**Comment by ROCKNROLLKID** [comment]
I have notified Shane about this.

**Comment by ROCKNROLLKID** [comment]
@ShaneGowland Are you still interested in doing this?

**Comment by ShaneGowland** [comment]
Yup. Thanks for the reminder.

**Comment by ShaneGowland** [comment]
I added the duplicate title checker. I don't have a GitHub client installed (switched to BitBucket), so I'll upload the two pertinent files here.

Didn't add the FileKey2-line-duplicates-within-entry detection, because winappdebug doesn't break the files into "entries," but rather tests each line as a standalone entity. In other words, I couldn't be bothered re-writing. It would, however, be very easy to add it to WinappParser, which I've been meaning to update for a while. Watch this space.

[WinappDebug.zip](https://github.com/MoscaDotTo/Winapp2/files/1167433/WinappDebug.zip)

**Comment by ROCKNROLLKID** [comment]
Thank you Shane. does you tool also check for missing brackets [] or asterisks * in file names, too? Might be another good thing to add.

**Comment by ROCKNROLLKID** [comment]
I realized I didn't upload the new WinappDebug. I just did it now. I will go ahead and close this as the original request was answered. If you have any new additions please open a new ticket.
