### ISSUE TITLE
GeForce Experience 3.0

### ISSUE THREAD

**Issue by TZocker** [MoscaDotTo/Winapp2#46]
We have to update all NVIDIA entries...
But don't delet old entires we need it for support old cards...

http://www.geforce.com/whats-new/articles/geforce-experience-3-0-released

Serval changes here :
C:\Users\Admin\AppData\Local\NVIDIA Corporation

and here...

C:\ProgramData\NVIDIA Corporation\

also here 

C:\ProgramData\NVIDIA

**Comment by ROCKNROLLKID** [comment]
I don't own a Nvidia card, so I don't know what will change. I am sure someone around the Piriform community will do. There is bound to be a few Nvidia users there.

For future reference, it is better to just write your own cleaners that you want, then just suggesting them, as we most likely won't know what needs to be cleaned or won't have the time to download and test it out themselves.

**Comment by MoscaDotTo** [comment]
Should we allow "request" posts? 

I'm personally for it, since it might provide a little more community engagement, but since I don't personally have much time to commit to fulfill many requests, I don't want to get ahead of myself. 

Of course, I'd say we'd need something more than just the name of a software to investigate cleaners for requests. Some kind of evidence it's actually leaving traces (MRUs, etc) 

Additionally, I think this could be a good way to begin moving entry discussion from the Piriform Forums to here, since it's a lot easier to keep track of code changes (whereas there's no consistent routine on the forums - sometimes people edit their previous posts, other times not. It can be difficult to track down the most recent version of a submission), since it the format would likely be pretty similar to forum posts (encouraging people like me who don't understand git to come over 😁 )

**Comment by ROCKNROLLKID** [comment]
The only problem is that if we don't know the program or never used it, then we might not know what damage it will be creating entries for it. We don't know what needs to be cleaned. I don't mind if they suggest cleaners though, but it's kind of useless if we don't know anything about the software/game to begin with.

I agree that moving everything to here would be more efficient, but I think the Piriform community prefers posting over at their forums.

Also, I see you merged those PRs from TZocker, but over at the Piriform forums we agreed to a 24 hour wait before adding entries to allow others to review first. Please see here: https://forum.piriform.com/index.php?showtopic=32310&p=276705

**Comment by MoscaDotTo** [comment]
Noted for future reference, I've been pretty absent on Piriform. One of the PRs was a versioning update for an existing entry and covered the same paths, so I didn't think much of it.

**Comment by TZocker** [comment]
OK 1. patch
https://github.com/MoscaDotTo/Winapp2/pull/50

also 
posted on forum...
