### ISSUE TITLE
Error when using Winapp2 in BleachBit

### ISSUE THREAD

**Issue by Gitoffthelawn** [MoscaDotTo/Winapp2#699]
Based on your feedback regarding CCleaner's limitations (thank you!), I gave BleachBit a try.

When adding Winapp2.ini to BleachBit Portable v3.2.0, the following error is displayed:

> parsing error in section Windows ShellBags *
Traceback (most recent call last):
  File "bleachbit\Winapp.pyo", line 172, in __init__
  File "bleachbit\Winapp.pyo", line 299, in handle_section
  File "bleachbit\Winapp.pyo", line 218, in excludekey_to_nwholeregex
NotImplementedError: REG not supported in ExcludeKey

**Comment by APMichael** [comment]
I'm sorry to hear that, but for that you have to contact the author of BleachBit:
https://github.com/bleachbit/bleachbit/issues

**Comment by Gitoffthelawn** [comment]
Hmmm... this seems to be a known incompatibility with BleachBit.  See https://github.com/bleachbit/bleachbit/issues/369

Consequently, if I'm understanding things correctly, the author of BleachBit has released his own Winapp2.ini.  See https://github.com/bleachbit/winapp2.ini

That doesn't seem ideal, because that Winapp2.ini won't automatically reflect the latest changes in this repo.

Any ideas?

BTW, what application(s) do you recommend using for Winapp2.ini on Linux and Windows that are fully compatible?  CCleaner has issues, as discussed in https://github.com/MoscaDotTo/Winapp2/issues/697, and BleachBit has issues as discussed here.

**Comment by APMichael** [comment]
I don't know if current versions of BleachBit still handle it that way. Did you add the Winapp2.ini as described in the ReadMe?

Unfortunately we can't do anything if a tool doesn't implement all functions. Winapp2.ini is an extension of CCleaner. We use the official CCleaner syntax, so CCleaner is fully compatible.

Winapp2.ini only works with Windows. It can't be used on systems with Linux, because Linux uses completely different paths.

**Comment by Gitoffthelawn** [comment]
Thanks for your help Michael.

Yes, BleachBit is choking a little on the Winapp2.ini in this repo.  After researching things more, it looks like the BleachBit author is really recommending using the Winapp2.ini in the BleachBit repo (which is actually the file named `Winapp2-BleachBit.ini`, and not the file named `Winapp2.ini` - a little confusing until I figured it out.

`Winapp2-BleachBit.ini` has too many edits to perform a simple text comparison with the `Winapp2.ini` in this repo. :-(

After comparing CCleaner and BleachBit, they each have their pros and cons.

CCleaner has much more "smarts", especially when it comes to it's default registry cleaning.  But all registry cleaning in CCleaner due to Winapp2.ini is really horrible... no preview or results.

BleachBit has some registry preview functionality, but it doesn't show a list of subkeys that will be deleted.  It starts up and processes Winapp2.ini much faster than CCleaner.  It's also open-source and fully free, which is very nice.

I'm not sure exactly how I'm going to proceed.  I'm interested in hearing back from the author of BleachBit as well.

Thank you again for all your help.

**Comment by APMichael** [comment]
You're welcome.

As written, a faster start of CCleaner can be achieved by using the Trim function of Winapp2ool.

The only possibility in the topic registry cleaning would be to look at the corresponding entries directly in the Winapp2.ini file.

After trimming the Winapp2.ini some people also build their own custom Winapp2.ini so that they have full control over what to delete. But then you have to add all updates yourself.
