### ISSUE TITLE
generic entries of CC identical to winapp2 & credentials deleted

### ISSUE THREAD

**Issue by Janaue** [MoscaDotTo/Winapp2#733]
Hello

I use CC on w10 1809 version 10.0.17763.1518 and winapp2+ winapp3, then I merge and trim them. Sometimes the generic entries from CC seem to do the same as some entries from winapp2. 
For instance, ''thumbnail cache'' is an option from CC and ''icon cache'' ''windows icon/thumbnail cache extended'' from winapp2 seem to be identical.

So if I want to keep the current cache, should I disable all those options ?
If i want to reset the cache, I need to enable only one option ?

There is the same situation with MUIcache and the backup of the positions of various windows and how they are set up.

I also have a difficulty with my credentials being deleted in Credential Manager, so after each run of CC, i need to import my credentials again. THere a several entries in CC and winapp2 which are about passwords and I can't pinpoint which ones delete my credentials.
I unchecked all the IE, edge entries for passwords and ''credentials'' entries and yet the credentials are deleted.

here is my winapp2 merged with winapp3
https://controlc.com/604d8c64
and my settings in CC
https://controlc.com/923d905e

**Comment by APMichael** [comment]
The entries are not identical. The Winapp2.ini (or Winapp3.ini) entries always delete more objects (files or registry keys) than the built-in entries. For example, the built-in entry "Thumbnail Cache" only deletes the files "thumbcache_\*.db", the Winapp2.ini entry "Icon Cache \*" deletes the files "iconcache_\*.db". Only together you get a complete cleanup. A single entry is not enough.

A Winapp3.ini entry usually deletes even more. In this case, however, under Windows 10 this no longer applies to the entry "Windows Icon/Thumbnail Cache Extended \*". Therefore this entry can be ignored under Windows 10.

Conclusion: If you don't want to delete anything, you should always disable all related entries. For a complete cleanup, on the other hand, normally all entries have to be enabled as well.

The problem with the deleted credentials is probably caused by the built-in entry "Network Passwords".
