### ISSUE TITLE
How to detect apps in non-standard installation paths?

### ISSUE THREAD

**Issue by Feathered-Serpent** [MoscaDotTo/Winapp2#745]
Greetings everyone,

I have organized my installed programs into categories like audio, video, graphics, network, security and so on.

Unfortunately this also means, the default detect file paths are not present for winapp2ool upon trimming.

Is there a way to let the program also check not only %programfiles% but also selectable other folders for the listed files and replace the %programfiles% if found? Would be the best if one could supply a list of folders which are checked one after another.

Example:
"%ProgramFiles%\Mozilla Firefox*|*.log" would be "C:\apps\network\Mozilla Firefox*|*.log" on my system.

Another example would be my steam game library, which is installed not onto the C drive. The games are found via registry key detection, but no files can ever be cleaned.

**Comment by MoscaDotTo** [comment]
winapp2.ini only supports default installation paths 

The simplest way to achieve what you want would be to create symbolic links from the default installation path to wherever you placed them 

eg. 

mklink /d "C:\program files\mozilla firefox" "C:\apps\network\mozilla firefox"

this would create a symlink which would allow ccleaner and winapp2ool to follow the default installation path but arrive at your chosen path. 

If your steam library is entirely in one place on another drive (eg. D:\games), you can symlink the steamapps folder. If your library is split between multiple drives (eg. D:\games\somegames\ AND e:\games\moregames) , you'll have to symlink the individual game subfolders from their default path to your installed path in order to have ccleaner find them all. 


Alternatively, maintaining a copy of winapp2.ini with the paths manually overridden (or find&replace macros to manually override the paths in a fresh copy of winapp2.ini) is an option but has much higher maintenance associated with it

**Comment by Feathered-Serpent** [comment]
I see.

What happens when I have multiple File1= entries for one app? Asking so I know if I can just duplicate the original line and then change the %programfiles% variable.

And when I do work with symbolic links, would it matter if I create the links at C:\Program Files or C:\Program Files (X86)?

**Comment by MoscaDotTo** [comment]
No, it won't matter. both ccleaner and winapp2ool check both directories when checking %programfiles% keys 

I'm not sure I understand your first question? You could simply find and replace every instance of %ProgramFiles%\Mozilla Firefox\ with C:\apps\mozilla firefox in a text editor. In order for this method to work, every instance must be replaced.

**Comment by Feathered-Serpent** [comment]
I just found out I can correct invalid FileX entries with the WinappDebug menu within winapp2ool.

Then I have all the information I need. Thank you for your replies!
