### ISSUE TITLE
Winapp2 & Chrome 69

### ISSUE THREAD

**Issue by Anony200023** [MoscaDotTo/Winapp2#846]
Since Chrome updated to version 96, I've been unable to delete Chrome cookies & temp internet files using ccleaner along with Winapp2.ini file. I'm using an old cCleaner version, 5.40.6411.

Can someone take a look at this?

**Comment by MoscaDotTo** [comment]
Cannot reproduce with Chrome 99 and CC 5.40, everything seems to be working fine. Did you change the path of your user directory for Chrome? 
![image](https://user-images.githubusercontent.com/529203/146935252-8dee173c-f187-4af5-ad6f-f0287ef33a00.png)

**Comment by Anony200023** [comment]
Sorry, I meant to say Chrome 96, not 69.
I didn't change the path of Chrome either.

Can you tell me the links that cookies should be in. Maybe I can look that up & see what's going on.

**Comment by APMichael** [comment]
I think everything has been answered so far in the forum:

https://community.ccleaner.com/topic/32310-winapp2ini-additions/page/343/#comment-333583

"I see that thinking, but winapp2 wouldn't normaly clean what CCleaner already cleans as standard, there wouldn't be much point in doing it twice. So you may be missing anything in CCleaner as standard that has changed since your old version. "

**Comment by Anony200023** [comment]
https://dfir.blog/cookies-database-moving-in-chrome-96/

**Comment by Anony200023** [comment]
OK, so I posted this at the ccleaner forums, but I'm asking this here as well.

The cookies file is now stored at C:\Users\Anon\AppData\Local\Google\Chrome\User Data\Profile 1\Network\cookies
Is there anyway I could create rules in the winapp2.ini file to have ccleaner delete this?

**Comment by APMichael** [comment]
For example, you can add the following entry to your Winapp2.ini:
```
[Network Cookies *]
LangSecRef=3029
DetectFile=%LocalAppData%\Google\Chrome*
FileKey1=%LocalAppData%\Google\Chrome*\User Data\*\Network|Cookies*
```

Or you can simply use the "Custom Files and Folders" feature of CCleaner:
https://support.piriform.com/hc/en-us/articles/360048231491-Select-files-and-folders-to-clean-with-CCleaner-for-Windows#adding-files-with-the-custom-files-and-folders-checkbox--0-2

**Comment by Anony200023** [comment]
Thank you so much for the help.

Just one more question. I have www.twitch.tv added to my exclude cookies list.
Is there anyway to add that exclusion or is that impossible with just the ini file or the "Custom Files and Folders" feature?

Can't believe I've had cCleaner for a decade & never saw that feature, lol.

**Comment by Anony200023** [comment]
Slightly OT but since I just figured this out:

Chrome Download History* doesn't work.

**Comment by APMichael** [comment]
> Thank you so much for the help.
> 
> Just one more question. I have [www.twitch.tv](http://www.twitch.tv) added to my exclude cookies list. Is there anyway to add that exclusion or is that impossible with just the ini file or the "Custom Files and Folders" feature?
> 
> Can't believe I've had cCleaner for a decade & never saw that feature, lol.

😄 You're welcome.

Unfortunately, no exclusions can be observed with it, since always only the complete database file can be deleted. (The exclusion list is a specially coded function of CCleaner, which can edit the database directly. However, we do not have access to this.)

> Slightly OT but since I just figured this out:
> 
> Chrome Download History* doesn't work.

This entry has been given a somewhat misleading name by its creator. It does not delete the download history visible in the browser, but a database that logs certain downloads. Therefore a name like "Download logging" would have been more appropriate.
