### ISSUE TITLE
MS Account problem

### ISSUE THREAD

**Issue by theLittlePrinceAD** [MoscaDotTo/Winapp2#940]
Using one and the same ccleaner.ini config file I run CCleaner 6.15 on a working Win 10 system:

1) - with removed winapp2.ini: no errors in MS account, no sign-out of MS account; MS Account/profile picture shows perfectly. 2 times restarted PC - still all working as expected.

2) - with updated winapp2.ini: after restart of system "MS To-Do" and "Sticky Notes" have been signed out of MS account, MS Account/profile picture has been removed.

My conclusion: the problem lies in "winapp2.ini" 

Some more info in CCleaner forum:
https://community.ccleaner.com/topic/32310-winapp2ini-additions/page/353/

**Comment by MoscaDotTo** [comment]
do you use a local account for windows (separate from logging into these apps) or a roaming account?

**Comment by theLittlePrinceAD** [comment]
> do you use a local account for windows (separate from logging into these apps) or a roaming account?

Roaming account.

**Comment by MoscaDotTo** [comment]
Does the most recent update resolve one or both of these issues?

**Comment by theLittlePrinceAD** [comment]
Hello,
Unfortunately all of the problems still exist (win 10 Pro):- missing profile picture  in Settings
- MS account problem in MS mail (MS store mail) -needs fixing- logged out of MS To Do, so have to sign in again.
BR

    On Wednesday, August 30, 2023 at 03:21:32 AM GMT+3, MoscaDotTo ***@***.***> wrote:  
 
 


Does the most recent update resolve one or both of these issues?

**Comment by theLittlePrinceAD** [comment]
To explain to my previous mail: I have downloaded winapp2.ini through CCEnhancer-4.5.7.exe trimming the data.Attached the result file (which as I explained is not working).

 
    On Wednesday, August 30, 2023 at 03:21:32 AM GMT+3, MoscaDotTo ***@***.***> wrote:  
 
 


Does the most recent update resolve one or both of these issues?

**Comment by theLittlePrinceAD** [comment]
Hello again,
I have several times restarted the PC, as well as shut it down, to check your winapp2 and all went perfectly, no errors on my side!I see you have found the problematic lines - thank you!
Regarding CCenhancer I have left it and am going to use your winapp2ool.One request if possible - to add possibility to save the newly trimmed winapp2.ini in a custom directory (f.e in the folder of CCleaner), so it would be possible to run winapp2ool silently updating the winapp2.ini used by CC enhancer.
Thanking you for all your work!BR


    On Wednesday, August 30, 2023 at 06:45:36 PM GMT+3, MoscaDotTo ***@***.***> wrote:  
 
 


CCEnhancer is developed by a different person and uses a different source for winapp2.ini. it's likely that source has not yet been updated

You can use winapp2ool to manage winapp2.ini for your system: https://github.com/MoscaDotTo/Winapp2/raw/master/winapp2ool/bin/Release/winapp2ool.exe

this tool is developed by me personally and uses the github copy of winapp2.ini as its source.

**Comment by MoscaDotTo** [comment]
yes this is possible. you can either place winapp2ool directly in the CCleaner directory (as it defaults to working on the winapp2.ini file in the current directory), open winapp2ool and configure the trim module to point to the ccleaner directory using the File Chooser, or launch winapp2ool with the commandline and provide the paths 

eg. 
`winapp2ool.exe -trim -d -s -3d "C:\program files\ccleaner\winapp2.ini" 

as a shortcut or from the command line will open winapp2ool's trim module silently, download the latest winapp2.ini from github, trim it for your system (CCEnhancer's Trim function does not support wildcards in DetectFiles) and save it to C:\Program Files\CCleaner\winapp2.ini

**Comment by theLittlePrinceAD** [comment]
Thank you very much for the advice, in the coming days I will have the time to apply it.BR and Good! 


    On Thursday, August 31, 2023 at 10:25:59 PM GMT+3, MoscaDotTo ***@***.***> wrote: 



yes this is possible. you can either place winapp2ool directly in the CCleaner directory (as it defaults to working on the winapp2.ini file in the current directory), open winapp2ool and configure the trim module to point to the ccleaner directory using the File Chooser, or launch winapp2ool with the commandline and provide the paths

eg.
`winapp2ool.exe -trim -d -s -3d "C:\program files\ccleaner\winapp2.ini"

as a shortcut or from the command line will open winapp2ool's trim module silently, download the latest winapp2.ini from github, trim it for your system (CCEnhancer's Trim function does not support wildcards in DetectFiles) and save it to C:\Program Files\CCleaner\winapp2.ini

**Comment by CSGalloway** [comment]
I am guessing:

 

 -trim  = trim winapp2 for the users system

 -d    = download winapp2.ini from github

 -s    = silently

 -3d  = ????
"C:\program files\ccleaner\winapp2.ini" = place to store the downloaded and 
trimed winapp2.ini 

 

----- Original Message -----
From: DIMOV, A.B. ***@***.***>
Reply-To: MoscaDotTo/Winapp2 
***@***.***>
To: MoscaDotTo/Winapp2 ***@***.***>
Cc: Subscribed ***@***.***>
Sent: 9/1/2023 1:06:51 PM
Subject: Re: [MoscaDotTo/Winapp2] MS Account problem (Issue #940)



Thank you very much for the advice, in the coming days I will have the time to 
apply it.BR and Good! 


On Thursday, August 31, 2023 at 10:25:59 PM GMT+3, MoscaDotTo ***@***.***> 
wrote: 



yes this is possible. you can either place winapp2ool directly in the CCleaner 
directory (as it defaults to working on the winapp2.ini file in the current 
directory), open winapp2ool and configure the trim module to point to the 
ccleaner directory using the File Chooser, or launch winapp2ool with the 
commandline and provide the paths 

eg. 
`winapp2ool.exe -trim -d -s -3d "C:\program files\ccleaner\winapp2.ini" 

as a shortcut or from the command line will open 
winapp2ool's trim module silently, download the latest winapp2.ini from github, trim it for your system (CCEnhancer's 
Trim function does not support wildcards in DetectFiles) and save it to 
C:\Program Files\CCleaner\winapp2.ini 

— 
Reply to this email directly, view it on GitHub, or unsubscribe. 
You are receiving this because you authored the thread.Message ID: ***@***.***> 

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: 
***@***.***>

**Comment by APMichael** [comment]
> -3d = ???? "C:\program files\ccleaner\winapp2.ini" = place to store the downloaded and trimed winapp2.ini

Correct, see documentation (even though it may be partially outdated):
https://github.com/MoscaDotTo/Winapp2/tree/master/winapp2ool/modules/trim#command-line-args

|Arg|Effect|
|:-|:-
`-3f` or `-3d`|Defines the path for the save file

|Name|Type|Default Value|Description|
|:-|:-|:-|:-
|TrimFile**3**|`iniFile`|`winapp2.ini` in the current directory|Holds the path where the output file will be saved to disk. Overwrites the input file by default
